#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Run as root or with sudo";
  exit 1;
fi

zone=$1
serial=`date +%Y%m%d`
file=/etc/bind/db.'"$zone"'.ward-scherens.sb.uclllabs.be
if test -f db.'"$zone"'.ward-scherens.sb.uclllabs.be; then
    echo 'Zone '"$zone"' already exists'
fi
#create zone in named.conf.local
echo "Adding zone"
echo -e 'zone "'"$zone"'.ward-scherens.sb.uclllabs.be" {
    type master;
    file "/etc/bind/zones/db.'"$zone"'.ward-scherens.sb.uclllabs.be";
    notify yes;
};
' >> /etc/bind/named.conf.local

#Create db. fileName
echo 'Creating :db.'"$zone"'.ward-scherens.sb.uclllabs.be' 
echo -e '$TTL 604800
@    IN    SOA    ns.'"$zone"'.ward-scherens.sb.uclllabs.be. root.'"$zone"'.ward-scherens.sb.uclllabs.be.(
           '"$serial"'    ; Serial
            300        ; Refresh
            300        ; Retry
            300        ; Expire
            300)        ; Negative Cache TTl
;
@    IN    NS    ns.'"$zone"'.ward-scherens.sb.uclllabs.be.
@    IN    NS    ns.ward-scherens.sb.uclllabs.be.
ns    IN    A    193.191.177.203
@    IN    A    193.191.177.203 ' > /etc/bind/zones/db.''"$zone"''.ward-scherens.sb.uclllabs.be

#update db file
echo -e ''"$zone"'    IN    NS    ns.ward-scherens.sb.uclllabs.be.' >> /etc/bind/db.ward-scherens.sb.uclllabs.be

#updating serial
seriall=$(grep "Serial" /etc/bind/db.ward-scherens.sb.uclllabs.be)
serialnumber=$(echo $seriall |sed 's/[^0-9]*//g')
((serialnumber++))
newserial="$serialnumber    ; Serial"
echo $newserial;
sed -i "s/.Serial./\t\t\t    $newserial/g" /etc/bind/db.ward-scherens.sb.uclllabs.be
echo -e 'serial updated'
#restarting bind9
echo 'Restart bind9 service'
systemctl restart bind9
echo "Ready"
