#!/bin/bash
#refuse to create vhost for non existing domain
exist=$(dig +short $1 @1.1.1.1)
#config vhost specific logging
if [ "$exist" = "193.191.177.203" ]; then
	echo "create vhost in sites available"
	echo -e '
	<VirtualHost *:80>
        	ServerName '"$1"'
        	ServerAlias '"$1"'
		DocumentRoot /var/www/html/'"$1"'
	
		ErrorLog ${APACHE_LOG_DIR}/'"$1"'-error.log
        	CustomLog ${APACHE_LOG_DIR}/'"$1"'-access.log combined
	</VirtualHost>' >> /etc/apache2/sites-available/$1.conf

	#create the correct documentroot dir
	echo -e 'create documentroot dir'
	mkdir /var/www/html/$1

	#create default index page and add the name of your vhost in it to allow automatic scoring
	echo -e 'create default index page'
	
	echo 'welcome '"$1"'' >> /var/www/html/$1/index.html

	echo -e 'create subzone folder under html'
	subzone='www.'$(echo "$1" | cut -d '.' -f 1-1)
	mkdir /var/www/html/$subzone
	echo "welcome $subzone" >> /var/www/html/$subzone/index.html

	#enable vhost
	echo -e 'enable vhost'
	a2ensite $1
	
	echo -e 'reload apache2'
	systemctl reload apache2
	echo 'done'
else 
	echo "Domain does not exist"
fi
